### ISSUE TITLE
gntp.errors.NetworkError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by MayukhSobo** [kfdm/gntp#61]
Hello I am getting this error. Please help me. I am new to this.

```python
import gntp.notifier
gntp.notifier.mini("Here's a quick message")
```

**Error:**

```sh
Growl error
Traceback (most recent call last):
  File "/Users/mayukhsarkar/anaconda3/lib/python3.6/site-packages/gntp/notifier.py", line 197, in _send
    s.connect((self.hostname, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mayukhsarkar/anaconda3/lib/python3.6/site-packages/gntp/notifier.py", line 243, in mini
    result = growl.register()
  File "/Users/mayukhsarkar/anaconda3/lib/python3.6/site-packages/gntp/notifier.py", line 98, in register
    return self._send('register', register)
  File "/Users/mayukhsarkar/anaconda3/lib/python3.6/site-packages/gntp/notifier.py", line 205, in _send
    raise errors.NetworkError(exc)
gntp.errors.NetworkError: [Errno 61] Connection refused
```

**Comment by kfdm** [comment]
Do you have [growl](http://growl.info/) running?
